# Azure Pipeline build file
# Ref: https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  branches:
    include:
    - master

variables:
- group: 'Release'

stages:
- stage: Build
  displayName: Build and Publish Docker image
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - job: Build_and_Publish
    displayName: Build and Publish Docker image
    variables:
    - group: 'Release'
    steps:
    - script: |
        echo dockerRegistry $(dockerRegistry)
    - task: Docker@2
      displayName: Login to Docker Hub
      inputs:
        command: login
        containerRegistry: '$(dockerRegistry)'
    - task: Docker@2
      displayName: Build and Publish image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        containerRegistry: '$(dockerRegistry)'
        repository: '$(dockerRepository)'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  displayName: Deploy App Service
  dependsOn: Build
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
  - deployment: Deploy
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)'
              containers: '$(dockerRepository):$(Build.BuildId)'
